//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Aksii
    {
        public int Id { get; set; }
        public byte[] BasePic { get; set; }
        public string TitleText { get; set; }
        public string ShortDescription { get; set; }
        public byte[] FullPic { get; set; }

        [UIHint("MultilineText")]
        [UIHint("tinymce_full"), AllowHtml]
        public string FullDescription { get; set; }
    }
}
