//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Clients
    {
        public int Id { get; set; }
        public string FamilyName { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string ContactPhone { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    }
}
