//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class CurrancyCode
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> ValueToSom { get; set; }
        public int CodeCur { get; set; }
    }
}
