//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Discount
    {
        public int id { get; set; }
        public string Id_Contraget { get; set; }
        public string Name_Contragent { get; set; }
        public Nullable<double> Discount1 { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Name_Artikul { get; set; }
        public string Name_Sklad { get; set; }
        public string Name_Service { get; set; }
        public Nullable<double> LimitPrice { get; set; }
    }
}
