//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [Serializable]
    public partial class FeedBack
    {
        public int FeedBackId { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Enter your name", AllowEmptyStrings = false)]
        public string FullName { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Mobile No")]
        public string MobilleNo { get; set; }

        [Display(Name = "States")]
        [Required(ErrorMessage = "Select your city", AllowEmptyStrings = false)]
        public string StateID { get; set; }
        public string Message { get; set; }
    }
}
