//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhaetonBrends
    {
        public int Id { get; set; }
        public string BrendName { get; set; }
        public Nullable<double> Markup { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    }
}
