//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class RemoteStore
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Brend { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public Nullable<int> Supplies { get; set; }
        public string MethodDelivery { get; set; }
        public Nullable<int> Existence { get; set; }
        public string Days { get; set; }
        public string V_P { get; set; }
        public Nullable<int> Min_Krat { get; set; }
        public Nullable<double> Price { get; set; }
        public string VIN { get; set; }
        public string CurrancyCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ViewOfContract { get; set; }
        public string Contragent { get; set; }
        public string Status { get; set; }
        public string Service { get; set; }
        public string Sklad { get; set; }
        public Nullable<int> Client { get; set; }
    }
}
