//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class StatusesL
    {
        public int Id { get; set; }
        public string NameStatus { get; set; }
        public bool IsCheck { get; set; }
    }
}
