//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UsersCARSEntities : DbContext
    {
        public UsersCARSEntities()
            : base("name=UsersCARSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Supplies> Supplies { get; set; }
        public virtual DbSet<ViewOfMade> ViewOfMade { get; set; }
        public virtual DbSet<ViewOfReport> ViewOfReport { get; set; }
        public virtual DbSet<Contraagent> Contraagent { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<StatusesL> StatusesL { get; set; }
        public virtual DbSet<NameOriginalAuto> NameOriginalAuto { get; set; }
        public virtual DbSet<UrlAutoOriginal> UrlAutoOriginal { get; set; }
        public virtual DbSet<DecoratedOrder> DecoratedOrder { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<RemoteStore> RemoteStore { get; set; }
        public virtual DbSet<CurrancyCode> CurrancyCode { get; set; }
        public virtual DbSet<Aksii> Aksii { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Brends> Brends { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
        public virtual DbSet<PhaetonBrends> PhaetonBrends { get; set; }
        public virtual DbSet<Remnants> Remnants { get; set; }
        public virtual DbSet<Analogue> Analogue { get; set; }
        public virtual DbSet<Analogs> Analogs { get; set; }
    
        public virtual ObjectResult<usmSelectDiscountBrend_Result> usmSelectDiscountBrend(string brend, Nullable<int> userID)
        {
            var brendParameter = brend != null ?
                new ObjectParameter("Brend", brend) :
                new ObjectParameter("Brend", typeof(string));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectDiscountBrend_Result>("usmSelectDiscountBrend", brendParameter, userIDParameter);
        }
    
        public virtual ObjectResult<usmSelectSearch_Result> usmSelectSearch(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectSearch_Result>("usmSelectSearch", codeParameter, brendProducerParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<usmSelectCurrancyCode_Result> usmSelectCurrancyCode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectCurrancyCode_Result>("usmSelectCurrancyCode");
        }
    
        public virtual ObjectResult<usmSelectNameOriginalAuto_Result> usmSelectNameOriginalAuto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectNameOriginalAuto_Result>("usmSelectNameOriginalAuto");
        }
    
        public virtual ObjectResult<usmSelectUserID_Result> usmSelectUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectUserID_Result>("usmSelectUserID", userIDParameter);
        }
    
        public virtual ObjectResult<usmSelectAllRemnants_Result> usmSelectAllRemnants()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllRemnants_Result>("usmSelectAllRemnants");
        }
    
        public virtual int uspBrendInsert(Nullable<int> userID, string code, string producer, string caption)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var producerParameter = producer != null ?
                new ObjectParameter("Producer", producer) :
                new ObjectParameter("Producer", typeof(string));
    
            var captionParameter = caption != null ?
                new ObjectParameter("Caption", caption) :
                new ObjectParameter("Caption", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspBrendInsert", userIDParameter, codeParameter, producerParameter, captionParameter);
        }
    
        public virtual ObjectResult<usmSelectBrendPhaeton_Result> usmSelectBrendPhaeton(string brendName)
        {
            var brendNameParameter = brendName != null ?
                new ObjectParameter("BrendName", brendName) :
                new ObjectParameter("BrendName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectBrendPhaeton_Result>("usmSelectBrendPhaeton", brendNameParameter);
        }
    
        public virtual ObjectResult<usmSelectBrendPhaetonByID_Result> usmSelectBrendPhaetonByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectBrendPhaetonByID_Result>("usmSelectBrendPhaetonByID", iDParameter);
        }
    
        public virtual ObjectResult<usmSelectAllRemnantsByStore000000001_Result> usmSelectAllRemnantsByStore000000001(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllRemnantsByStore000000001_Result>("usmSelectAllRemnantsByStore000000001", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmSelectAllRemnantsByStore000000002_Result> usmSelectAllRemnantsByStore000000002(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllRemnantsByStore000000002_Result>("usmSelectAllRemnantsByStore000000002", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmSelectAllRemnantsByStore000000005_Result> usmSelectAllRemnantsByStore000000005(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllRemnantsByStore000000005_Result>("usmSelectAllRemnantsByStore000000005", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmSelectAllRemnantsByStore000000006_Result> usmSelectAllRemnantsByStore000000006(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllRemnantsByStore000000006_Result>("usmSelectAllRemnantsByStore000000006", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmSelectBrendPhaeton1_Result> usmSelectBrendPhaeton1(string brendName)
        {
            var brendNameParameter = brendName != null ?
                new ObjectParameter("BrendName", brendName) :
                new ObjectParameter("BrendName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectBrendPhaeton1_Result>("usmSelectBrendPhaeton1", brendNameParameter);
        }
    
        public virtual ObjectResult<usmSelectBrendPhaetonByID1_Result> usmSelectBrendPhaetonByID1(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectBrendPhaetonByID1_Result>("usmSelectBrendPhaetonByID1", iDParameter);
        }
    
        public virtual ObjectResult<usmSelectSaleByArticul_Result> usmSelectSaleByArticul(string articul)
        {
            var articulParameter = articul != null ?
                new ObjectParameter("Articul", articul) :
                new ObjectParameter("Articul", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectSaleByArticul_Result>("usmSelectSaleByArticul", articulParameter);
        }
    
        public virtual ObjectResult<usmAllianceSelectAllRemnantsByStore000000001_Result> usmAllianceSelectAllRemnantsByStore000000001(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmAllianceSelectAllRemnantsByStore000000001_Result>("usmAllianceSelectAllRemnantsByStore000000001", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmAllianceSelectAllRemnantsByStore000000002_Result> usmAllianceSelectAllRemnantsByStore000000002(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmAllianceSelectAllRemnantsByStore000000002_Result>("usmAllianceSelectAllRemnantsByStore000000002", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmAllianceSelectAllRemnantsByStore000000005_Result> usmAllianceSelectAllRemnantsByStore000000005(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmAllianceSelectAllRemnantsByStore000000005_Result>("usmAllianceSelectAllRemnantsByStore000000005", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmAllianceSelectAllRemnantsByStore000000006_Result> usmAllianceSelectAllRemnantsByStore000000006(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmAllianceSelectAllRemnantsByStore000000006_Result>("usmAllianceSelectAllRemnantsByStore000000006", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmSelectAllRemnantsByStoreMinSklad_Result> usmSelectAllRemnantsByStoreMinSklad(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllRemnantsByStoreMinSklad_Result>("usmSelectAllRemnantsByStoreMinSklad", codeParameter, brendProducerParameter);
        }
    
        public virtual int usm_TempTableAnalogRemnantsInsert(string code, string brendProducer, string name, Nullable<int> numOfAnalog)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numOfAnalogParameter = numOfAnalog.HasValue ?
                new ObjectParameter("NumOfAnalog", numOfAnalog) :
                new ObjectParameter("NumOfAnalog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usm_TempTableAnalogRemnantsInsert", codeParameter, brendProducerParameter, nameParameter, numOfAnalogParameter);
        }
    
        public virtual int uspAllianceTempTableAnalog(string code, string brendProducer, string name, Nullable<int> numOfAnalog)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numOfAnalogParameter = numOfAnalog.HasValue ?
                new ObjectParameter("NumOfAnalog", numOfAnalog) :
                new ObjectParameter("NumOfAnalog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAllianceTempTableAnalog", codeParameter, brendProducerParameter, nameParameter, numOfAnalogParameter);
        }
    
        public virtual ObjectResult<uspAllianceTempTableAnalog1_Result> uspAllianceTempTableAnalog1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspAllianceTempTableAnalog1_Result>("uspAllianceTempTableAnalog1");
        }
    
        public virtual int usm_AnalogRemnantsInsert1(string code, string brendProducer, string name, Nullable<int> numOfAnalog)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numOfAnalogParameter = numOfAnalog.HasValue ?
                new ObjectParameter("NumOfAnalog", numOfAnalog) :
                new ObjectParameter("NumOfAnalog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usm_AnalogRemnantsInsert1", codeParameter, brendProducerParameter, nameParameter, numOfAnalogParameter);
        }
    
        public virtual int usm_AnalogRemnantsInsert(string code, string brendProducer, string name, Nullable<int> numOfAnalog)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numOfAnalogParameter = numOfAnalog.HasValue ?
                new ObjectParameter("NumOfAnalog", numOfAnalog) :
                new ObjectParameter("NumOfAnalog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usm_AnalogRemnantsInsert", codeParameter, brendProducerParameter, nameParameter, numOfAnalogParameter);
        }
    
        public virtual ObjectResult<usmAnalogRemnantsInsert_1_Result> usmAnalogRemnantsInsert_1(string code, string brendProducer, string name, Nullable<int> numOfAnalog)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var numOfAnalogParameter = numOfAnalog.HasValue ?
                new ObjectParameter("NumOfAnalog", numOfAnalog) :
                new ObjectParameter("NumOfAnalog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmAnalogRemnantsInsert_1_Result>("usmAnalogRemnantsInsert_1", codeParameter, brendProducerParameter, nameParameter, numOfAnalogParameter);
        }
    
        public virtual int usmAnalogRemnantsInsert_Array1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogRemnantsInsert_Array1");
        }
    
        public virtual int usmAnalogRemnantsInsert_Array()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogRemnantsInsert_Array");
        }
    
        public virtual int usmAnalogInsert_Array()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogInsert_Array");
        }
    
        public virtual int usmAnalogInsert_Array1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogInsert_Array1");
        }
    
        public virtual int usmAnalogInsert_Array_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogInsert_Array_2");
        }
    
        public virtual int usmAnalogInsert_Array_new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogInsert_Array_new");
        }
    
        public virtual int usmAnalogInsert_Array_new1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogInsert_Array_new1");
        }
    
        public virtual int usmAnalogInsert_Array_2new()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usmAnalogInsert_Array_2new");
        }
    
        public virtual ObjectResult<usmSelectAllAnalogsMinSklad_Result> usmSelectAllAnalogsMinSklad(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllAnalogsMinSklad_Result>("usmSelectAllAnalogsMinSklad", codeParameter, brendProducerParameter);
        }
    
        public virtual ObjectResult<usmSelectAllAnalogsMinSklad1_Result> usmSelectAllAnalogsMinSklad1(string code, string brendProducer)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var brendProducerParameter = brendProducer != null ?
                new ObjectParameter("BrendProducer", brendProducer) :
                new ObjectParameter("BrendProducer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usmSelectAllAnalogsMinSklad1_Result>("usmSelectAllAnalogsMinSklad1", codeParameter, brendProducerParameter);
        }
    }
}
