//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [Serializable]
    public partial class Vacancies
    {
        public int Id { get; set; }
        public string Title { get; set; }

        [UIHint("MultilineText")]
        [UIHint("tinymce_full"), AllowHtml]
        public string Demands { get; set; }

        [UIHint("MultilineText")]
        [UIHint("tinymce_full"), AllowHtml]
        public string Duties { get; set; }

        [UIHint("MultilineText")]
        [UIHint("tinymce_full"), AllowHtml]
        public string WorkConditions { get; set; }
    }
}
